set_property PACKAGE_PIN U16 [get_ports ld0]
set_property PACKAGE_PIN V16 [get_ports sw0]
set_property PACKAGE_PIN V17 [get_ports sw1]
set_property IOSTANDARD LVTTL [get_ports ld0]
set_property IOSTANDARD LVTTL [get_ports sw0]
set_property IOSTANDARD LVTTL [get_ports sw1]
set_property IOSTANDARD LVTTL [get_ports {mode[1]}]
set_property IOSTANDARD LVTTL [get_ports {mode[0]}]

set_property PACKAGE_PIN R2 [get_ports {mode[2]}]
set_property PACKAGE_PIN T1 [get_ports {mode[1]}]
set_property PACKAGE_PIN U1 [get_ports {mode[0]}]
set_property IOSTANDARD LVTTL [get_ports {mode[2]}]
